# SPDX-FileCopyrightText: 2026 Cyprien PIERRE
#
# SPDX-License-Identifier: CECILL-2.1

"""Check that declared index terms occur in the manuscript corpus.

The index is generated by tools/SpecExt/AutoMark.lean from
tools/SpecExt/IndexTerms.lean. The control deliberately excludes the generated reference
listings from the prose corpus and applies the same broad matching rule used by the index core:
word boundaries, case/diacritic folding and an optional plural mark.

A small set of terms is currently retained in the index while absent from the running text. Those
exceptions are explicit and reviewed here rather than being silently ignored. They are expected to
be removed from this set when the manuscript vocabulary is reconciled with the index.
"""

from __future__ import annotations

import re
import unicodedata

from . import corpus
from .journal import ko, ok

TERMS_FILE = corpus.SPEC.parent / "tools" / "SpecExt" / "IndexTerms.lean"
LISTINGS = ("Refs.",)

# Terms retained in the index although the current prose does not contain them verbatim.
# This is a temporary, explicit exception list: it is not a substitute for maintaining the index.
KNOWN_ABSENT = {
    "analyse de coût",
    "cohérence de la subsomption",
    "effacement de phase",
}


def fold(text: str) -> str:
    text = unicodedata.normalize("NFKD", text.replace("\u00a0", " ").replace("’", "'"))
    return "".join(c for c in text if not unicodedata.combining(c)).lower()


def terms() -> list[str]:
    source = TERMS_FILE.read_text(encoding="utf-8")
    block = source[source.index("#[") : source.index("].map")]
    return re.findall(r'"([^"]+)"', block)


def run() -> None:
    print("\n[Index]")
    listed = terms()
    listed_set = set(listed)
    stale_exceptions = sorted(KNOWN_ABSENT - listed_set)
    if stale_exceptions:
        ko("exceptions d'index obsolètes : %s" % stale_exceptions)
        return

    prose = fold(
        "\n".join(t for name, _, t in corpus.modules() if not name.startswith(LISTINGS))
    )
    absent = [
        t
        for t in listed
        if not re.search(
            r"(?<![a-z0-9])"
            + re.escape(fold(t))
            + r"[sx]?(?![a-z0-9])",
            prose,
        )
    ]
    unknown = [t for t in absent if t not in KNOWN_ABSENT]
    if unknown:
        ko("termes de l'index absents du texte : %s" % unknown)
    else:
        known = sorted(KNOWN_ABSENT & set(absent))
        ok(
            "index : %d termes, %d présents dans le texte, absents connus : %s"
            % (len(listed), len(listed) - len(absent), known)
        )
