# SPDX-FileCopyrightText: 2026 Cyprien PIERRE
#
# SPDX-License-Identifier: CECILL-2.1

"""Offline tests for scripts/sync_zenodo.py.

Standard library only. `requests` is replaced by a double injected into `sys.modules` before the
script is imported, so no network access is possible: a call that no route answers raises
`AssertionError`. A Zenodo DOI is irreversible, so the properties that matter most are the
refusals: for each of them the double must have recorded no call at all.
"""

import contextlib
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import types
import unittest
from pathlib import Path
from unittest import mock

SCRIPTS = Path(__file__).resolve().parents[1]


class FakeHTTPError(Exception):
    """Stands for requests.HTTPError."""


class FakeResponse:
    def __init__(self, payload=None, status=200, text=""):
        self._payload = payload
        self.status_code = status
        self.ok = status < 400
        self.text = text

    def json(self):
        return self._payload

    def raise_for_status(self):
        if not self.ok:
            error = FakeHTTPError(f"HTTP {self.status_code}")
            error.response = self  # like requests.HTTPError, which carries the response
            raise error


class FakeRequests:
    """Records every call. Subclasses answer through `dispatch`; the base class answers nothing."""

    HTTPError = FakeHTTPError

    def __init__(self):
        self.calls = []

    def dispatch(self, method, url, **kwargs):
        raise AssertionError(f"unexpected network call: {method} {url}")

    def _call(self, method, url, **kwargs):
        self.calls.append((method, url, kwargs))
        return self.dispatch(method, url, **kwargs)

    def get(self, url, **kwargs):
        return self._call("GET", url, **kwargs)

    def post(self, url, **kwargs):
        return self._call("POST", url, **kwargs)

    def put(self, url, **kwargs):
        return self._call("PUT", url, **kwargs)

    def delete(self, url, **kwargs):
        return self._call("DELETE", url, **kwargs)

    def operations(self):
        return [(method, url.split("/api/", 1)[-1]) for method, url, _ in self.calls]


# The script is imported with the double in place, then `requests` is put back as it was.
_previous = sys.modules.get("requests")
_stub = types.ModuleType("requests")
_stub.HTTPError = FakeHTTPError
sys.modules["requests"] = _stub
sys.path.insert(0, str(SCRIPTS))
try:
    import sync_zenodo
finally:
    sys.path.remove(str(SCRIPTS))
    if _previous is None:
        del sys.modules["requests"]
    else:
        sys.modules["requests"] = _previous

BASE = "https://sandbox.zenodo.org"
API = f"{BASE}/api"
PDF_BYTES = b"%PDF-1.7 fake pdf for the tests\n"
PDF_SHA256 = hashlib.sha256(PDF_BYTES).hexdigest()
PDF_MD5 = hashlib.md5(PDF_BYTES).hexdigest()  # noqa: S324 - Zenodo reports MD5 sums
TOKEN = "tok-secret-0123456789"
TAG = "spec-v0.1.0"
COMMIT = "ab" * 20
RELEASE_URL = "https://github.com/owner/repo/releases/tag/spec-v0.1.0"
BASE_ZENODO_JSON = {
    "title": "K7PL",
    "creators": [{"name": "Pierre, Cyprien"}],
    "notes": "Generated by the CI.",
    "related_identifiers": [
        {"identifier": "https://github.com/owner/repo", "relation": "isSupplementTo", "scheme": "url"}
    ],
}


UNSET = object()


class FakeZenodo(FakeRequests):
    """A just-enough Zenodo: NEW concept (record 777) or new version of concept 100 (latest 222,
    draft 333). Options inject the misbehaviours the script must refuse."""

    def __init__(
        self,
        concept=None,
        record_concept=None,
        checksum="md5",
        draft_link=UNSET,
        draft_id=333,
        concept_status=200,
        old_file_id="oldfile",
        latest_related=None,
        readback_status=200,
        delete_status=204,
        record_link=UNSET,
        publish_error=None,
        publish_status=200,
        readback_error=None,
        publish_payload=UNSET,
        readback_payload=UNSET,
    ):
        super().__init__()
        self.publish_payload = publish_payload
        self.readback_payload = readback_payload
        self.delete_status = delete_status
        self.record_link = record_link
        self.publish_error = publish_error
        self.publish_status = publish_status
        self.readback_error = readback_error
        self.latest_related = latest_related
        self.readback_status = readback_status
        self.concept = concept
        self.record_concept = record_concept if record_concept is not None else concept
        self.checksum = checksum
        self.draft_link = draft_link
        self.draft_id = draft_id
        self.concept_status = concept_status
        self.old_file_id = old_file_id
        self.metadata = None
        self.uploaded = None
        self.published_id = 777 if concept is None else 333

    def checksum_value(self):
        return {
            "md5": PDF_MD5,
            "md5-prefixed": f"md5:{PDF_MD5}",
            "wrong": "0" * 32,
            "none": None,
            "garbage": "not-a-checksum",
            "listing-md5": PDF_MD5,  # only the file listing carries it, not the upload answer
            "listing-wrong": "0" * 32,
        }[self.checksum]

    def published_record(self):
        return {
            "id": self.published_id,
            "doi": f"10.5281/zenodo.{self.published_id}",
            "conceptdoi": "10.5281/zenodo.100" if self.concept else "10.5281/zenodo.776",
            "conceptrecid": 100 if self.concept else 776,
        }

    def dispatch(self, method, url, **kwargs):
        assert url.startswith(API + "/"), f"call outside the configured instance: {url}"
        path = url[len(API):]
        if method == "POST" and path == "/deposit/depositions":
            self.metadata = kwargs["json"]["metadata"]
            return FakeResponse({"id": 777, "links": {}})
        if method == "GET" and path == f"/records/{self.concept}":
            record = {"id": 222, "conceptrecid": self.record_concept}
            if self.latest_related is not None:
                record["metadata"] = {"related_identifiers": self.latest_related}
            return FakeResponse(record, status=self.concept_status)
        if method == "POST" and path == "/deposit/depositions/222/actions/newversion":
            link = (
                f"{API}/deposit/depositions/{self.draft_id}"
                if self.draft_link is UNSET
                else self.draft_link
            )
            return FakeResponse({"links": {"latest_draft": link}})
        if method == "GET" and re.fullmatch(r"/deposit/depositions/\d+", path):
            return FakeResponse({"id": self.draft_id})
        if method == "PUT" and re.fullmatch(r"/deposit/depositions/\d+", path):
            self.metadata = kwargs["json"]["metadata"]
            return FakeResponse({"id": self.draft_id})
        if method == "GET" and re.fullmatch(r"/deposit/depositions/\d+/files", path):
            inherited = (
                [] if self.concept is None else [{"id": self.old_file_id, "filename": "old.pdf"}]
            )
            if self.uploaded is not None:
                inherited.append(self.uploaded)
            return FakeResponse(inherited)
        if method == "DELETE" and re.fullmatch(r"/deposit/depositions/\d+/files/\w+", path):
            return FakeResponse(None, status=self.delete_status)
        if method == "POST" and re.fullmatch(r"/deposit/depositions/\d+/files", path):
            content = kwargs["files"]["file"].read()
            assert content == PDF_BYTES, "the uploaded bytes are not the local file"
            entry = {"id": "newfile", "filename": kwargs["data"]["name"]}
            stored = dict(entry)
            if self.checksum_value() is not None:
                stored["checksum"] = self.checksum_value()
                if not self.checksum.startswith("listing-"):
                    entry["checksum"] = self.checksum_value()
            self.uploaded = stored
            return FakeResponse(entry)
        if method == "POST" and re.fullmatch(r"/deposit/depositions/\d+/actions/publish", path):
            if self.publish_error is not None:
                raise self.publish_error
            if self.publish_payload is not UNSET:
                return FakeResponse(self.publish_payload)
            record = self.published_id
            payload = self.published_record()
            payload["links"] = {
                "record": f"{API}/records/{record}" if self.record_link is UNSET else self.record_link
            }
            return FakeResponse(payload, status=self.publish_status)
        if method == "GET" and path == f"/records/{self.published_id}":
            if self.readback_error is not None:
                raise self.readback_error
            if self.readback_payload is not UNSET:
                return FakeResponse(self.readback_payload)
            return FakeResponse(self.published_record(), status=self.readback_status)
        raise AssertionError(f"unexpected route: {method} {path}")


class ZenodoTestCase(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.tmp = Path(tmp.name)
        (self.tmp / "out").mkdir()
        (self.tmp / "out" / "k7pl-spec.pdf").write_bytes(PDF_BYTES)
        (self.tmp / "zenodo.json").write_text(json.dumps(BASE_ZENODO_JSON), encoding="utf-8")
        self.zenodo_json_before = (self.tmp / "zenodo.json").read_bytes()
        previous = os.getcwd()
        os.chdir(self.tmp)
        self.addCleanup(os.chdir, previous)

    def env(self, **overrides):
        env = {
            "ZENODO_TOKEN": TOKEN,
            "ZENODO_ENV": "sandbox",
            "ZENODO_CONCEPT_RECID": "NEW",
            "ZENODO_TAG": TAG,
            "ZENODO_COMMIT": COMMIT,
            "ZENODO_REPOSITORY": "owner/repo",
            "ZENODO_RELEASE_URL": RELEASE_URL,
            "GITHUB_RUN_ATTEMPT": "1",
            "ZENODO_FILES_DIR": "out",
            "GITHUB_STEP_SUMMARY": str(self.tmp / "summary.md"),
        }
        env.update(overrides)
        return {k: v for k, v in env.items() if v is not None}

    def run_script(self, fake, environ, argv=()):
        """(exit status, stdout, stderr); the double replaces `requests` for the whole run."""
        out, err = io.StringIO(), io.StringIO()
        with mock.patch.object(sync_zenodo, "requests", fake):
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                status = sync_zenodo.run(list(argv), environ)
        self.assertNotIn(TOKEN, out.getvalue() + err.getvalue(), "the token must never be printed")
        return status, out.getvalue(), err.getvalue()

    def assert_refused_before_network(self, environ, message, argv=(), status=2):
        fake = FakeRequests()
        code, _, err = self.run_script(fake, environ, argv)
        self.assertEqual(fake.calls, [], "a refusal must not reach the network")
        self.assertEqual(code, status)
        self.assertIn(message, err)

    def summary(self):
        path = self.tmp / "summary.md"
        return path.read_text(encoding="utf-8") if path.exists() else ""


class ConfigurationRefusalTests(ZenodoTestCase):
    def test_the_good_environment_is_accepted_by_the_check(self):
        # Positive control: the refusals below are caused by the property they name.
        fake = FakeRequests()
        code, out, _ = self.run_script(fake, self.env(ZENODO_TOKEN=None), ["--check-config"])
        self.assertEqual((code, fake.calls), (0, []))
        self.assertIn("Configuration OK", out)

    def test_missing_concept_recid_fails_before_any_network_call(self):
        self.assert_refused_before_network(self.env(ZENODO_CONCEPT_RECID=None), "ZENODO_CONCEPT_RECID is not set")

    def test_empty_concept_recid_fails_before_any_network_call(self):
        self.assert_refused_before_network(self.env(ZENODO_CONCEPT_RECID=""), "ZENODO_CONCEPT_RECID is not set")

    def test_non_numeric_concept_recid_is_refused(self):
        bad = ["abc", "12a", "-5", "0", "012", "1.5", " 123", "123 ", "123\n", "new", "NEW ", "1e9",
               "123/../x", "123?x=1", "0x10", "٣٣", "9" * 19, "1,2"]
        for value in bad:
            with self.subTest(value=value):
                self.assert_refused_before_network(
                    self.env(ZENODO_CONCEPT_RECID=value), "positive integer or the literal NEW"
                )

    def test_invalid_environment_name_is_refused_without_falling_back_to_production(self):
        for value in (None, "", "prod", "Production", "SANDBOX", "staging", "sandbox ", "https://zenodo.org"):
            with self.subTest(value=value):
                self.assert_refused_before_network(
                    self.env(ZENODO_ENV=value), "ZENODO_ENV must be exactly 'production' or 'sandbox'"
                )

    def test_both_valid_environments_select_their_own_instance(self):
        for name, base in (("production", "https://zenodo.org"), ("sandbox", "https://sandbox.zenodo.org")):
            with self.subTest(env=name):
                config = sync_zenodo.load_config(self.env(ZENODO_ENV=name))
                self.assertEqual(config.api, f"{base}/api")

    def test_a_token_with_a_line_break_or_a_space_is_refused_without_being_shown(self):
        for token in ("S3CRETtoken\n", "S3CRET token", "S3CRET\ttoken", "S3CRET\x00", "S3CRET\u00e9"):
            with self.subTest(token=token):
                fake = FakeRequests()
                code, _, err = self.run_script(fake, self.env(ZENODO_TOKEN=token))
                self.assertEqual((code, fake.calls), (2, []))
                self.assertIn("ZENODO_TOKEN contains", err)
                self.assertNotIn("S3CRET", err)
        self.assertEqual(self.run_script(FakeRequests(), self.env(), ["--check-config"])[0], 0)

    def test_the_token_is_not_part_of_the_repr_of_the_configuration(self):
        config = sync_zenodo.load_config(self.env())
        self.assertNotIn(TOKEN, repr(config))
        self.assertEqual(config.token, TOKEN)

    def test_missing_token_is_refused_before_any_network_call(self):
        self.assert_refused_before_network(self.env(ZENODO_TOKEN=None), "ZENODO_TOKEN is not set")
        self.assert_refused_before_network(self.env(ZENODO_TOKEN=""), "ZENODO_TOKEN is not set")

    def test_malformed_release_facts_are_refused(self):
        cases = [
            ({"ZENODO_TAG": "v0.1.0"}, "ZENODO_TAG"),
            ({"ZENODO_TAG": "spec-v"}, "ZENODO_TAG"),
            ({"ZENODO_TAG": "spec-v1 2"}, "ZENODO_TAG"),
            ({"ZENODO_TAG": None}, "ZENODO_TAG"),
            ({"ZENODO_VERSION": "9.9.9"}, "does not match the tag"),
            ({"ZENODO_COMMIT": "abc123"}, "ZENODO_COMMIT"),
            ({"ZENODO_COMMIT": "AB" * 20}, "ZENODO_COMMIT"),
            ({"ZENODO_REPOSITORY": "no-slash"}, "ZENODO_REPOSITORY"),
            ({"ZENODO_REPOSITORY": "a/b/c"}, "ZENODO_REPOSITORY"),
            ({"ZENODO_RELEASE_URL": "https://evil.example/owner/repo/releases/tag/x"}, "ZENODO_RELEASE_URL"),
            ({"ZENODO_RELEASE_URL": "http://github.com/owner/repo/releases/tag/x"}, "ZENODO_RELEASE_URL"),
            ({"ZENODO_RELEASE_URL": RELEASE_URL + " extra"}, "ZENODO_RELEASE_URL"),
        ]
        for overrides, message in cases:
            with self.subTest(overrides=overrides):
                self.assert_refused_before_network(self.env(**overrides), message)

    def test_version_is_taken_from_the_tag_and_may_be_restated(self):
        self.assertEqual(sync_zenodo.load_config(self.env()).version, "0.1.0")
        self.assertEqual(sync_zenodo.load_config(self.env(ZENODO_VERSION="0.1.0")).version, "0.1.0")

    def test_check_config_refuses_what_a_real_run_refuses(self):
        self.assert_refused_before_network(
            self.env(ZENODO_CONCEPT_RECID="abc"), "positive integer", argv=["--check-config"]
        )

    def test_no_pdf_and_several_pdfs_are_refused_before_any_network_call(self):
        (self.tmp / "out" / "k7pl-spec.pdf").unlink()
        self.assert_refused_before_network(self.env(), "No PDF found", status=1)
        (self.tmp / "out" / "a.pdf").write_bytes(PDF_BYTES)
        (self.tmp / "out" / "b.pdf").write_bytes(PDF_BYTES)
        self.assert_refused_before_network(self.env(), "one concept record holds one document", status=1)


class NewConceptTests(ZenodoTestCase):
    def test_explicit_new_creates_a_record_and_never_looks_up_a_concept(self):
        fake = FakeZenodo(concept=None)
        code, out, _ = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="NEW"))
        self.assertEqual(code, 0)
        self.assertEqual(
            fake.operations(),
            [
                ("POST", "deposit/depositions"),
                ("GET", "deposit/depositions/777/files"),
                ("POST", "deposit/depositions/777/files"),
                ("POST", "deposit/depositions/777/actions/publish"),
                ("GET", "records/777"),
            ],
        )
        self.assertIn("10.5281/zenodo.777", out)

    def test_new_asks_the_author_to_record_the_created_concept(self):
        self.run_script(FakeZenodo(concept=None), self.env(ZENODO_CONCEPT_RECID="NEW"))
        summary = self.summary()
        self.assertIn("ZENODO_CONCEPT_RECID", summary)
        self.assertIn("`776`", summary)  # the concept record id created by the double
        self.assertIn(PDF_SHA256, summary)
        self.assertIn(TAG, summary)

    def test_run_time_identifiers_and_digest_reach_the_record_and_zenodo_json_is_untouched(self):
        fake = FakeZenodo(concept=None)
        self.run_script(fake, self.env())
        meta = fake.metadata
        identifiers = {(i["identifier"], i["relation"]) for i in meta["related_identifiers"]}
        self.assertIn(("https://github.com/owner/repo/tree/spec-v0.1.0", "isSupplementTo"), identifiers)
        self.assertIn((f"https://github.com/owner/repo/commit/{COMMIT}", "isDerivedFrom"), identifiers)
        self.assertIn((RELEASE_URL, "isIdenticalTo"), identifiers)
        self.assertIn(("https://github.com/owner/repo", "isSupplementTo"), identifiers)  # kept
        self.assertTrue(all(i["scheme"] == "url" for i in meta["related_identifiers"]))
        self.assertIn(PDF_SHA256, meta["notes"])
        self.assertIn(COMMIT, meta["notes"])
        self.assertTrue(meta["notes"].startswith("Generated by the CI."))
        self.assertEqual(meta["version"], "0.1.0")
        self.assertEqual((self.tmp / "zenodo.json").read_bytes(), self.zenodo_json_before)
        self.assertEqual(len(BASE_ZENODO_JSON["related_identifiers"]), 1)  # the input was not mutated

    def test_the_digest_in_the_notes_is_that_of_the_published_bytes(self):
        fake = FakeZenodo(concept=None)
        self.run_script(fake, self.env())
        recorded = re.search(r"SHA-256 du PDF \(k7pl-spec\.pdf\) : ([0-9a-f]{64})", fake.metadata["notes"])
        self.assertEqual(recorded.group(1), hashlib.sha256(PDF_BYTES).hexdigest())


class NewVersionTests(ZenodoTestCase):
    def test_declared_concept_gets_a_new_version_and_no_new_record(self):
        fake = FakeZenodo(concept=100)
        code, out, _ = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(code, 0)
        operations = fake.operations()
        self.assertEqual(operations[0], ("GET", "records/100"))
        self.assertIn(("POST", "deposit/depositions/222/actions/newversion"), operations)
        self.assertNotIn(("POST", "deposit/depositions"), operations)  # never a new record
        self.assertIn(("DELETE", "deposit/depositions/333/files/oldfile"), operations)  # inherited file
        self.assertIn(("POST", "deposit/depositions/333/actions/publish"), operations)
        self.assertNotIn("**Action requise**", self.summary())
        self.assertIn("10.5281/zenodo.333", out)

    def test_a_version_id_given_instead_of_the_concept_id_is_refused_before_any_write(self):
        fake = FakeZenodo(concept=100, record_concept=99)
        code, _, err = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(code, 1)
        self.assertIn("belongs to concept 99", err)
        self.assertEqual(fake.operations(), [("GET", "records/100")])

    def test_an_unreadable_concept_never_falls_back_to_creating_a_record(self):
        fake = FakeZenodo(concept=100, concept_status=404)
        with self.assertRaises(FakeHTTPError):
            self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(fake.operations(), [("GET", "records/100")])

    def test_a_draft_link_to_another_host_is_not_followed(self):
        for link in (
            "https://evil.example/api/deposit/depositions/333",
            f"{BASE}.evil.example/api/deposit/depositions/333",
            "http://sandbox.zenodo.org/api/deposit/depositions/333",
            "https://user@sandbox.zenodo.org/api/deposit/depositions/333",
            f"{BASE}/api/records/333",
            f"{BASE}/api/deposit/depositions/333/../../x",
            f"{BASE}/api/deposit/depositions/abc",
            None,
        ):
            with self.subTest(link=link):
                fake = FakeZenodo(concept=100, draft_link=link)
                code, _, err = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
                self.assertEqual(code, 1, err)
                self.assertTrue(all(url.startswith(API + "/") for _, url, _ in fake.calls))
                self.assertNotIn(("POST", "deposit/depositions/333/actions/publish"), fake.operations())

    def test_a_non_numeric_draft_id_is_refused_before_it_reaches_a_url(self):
        fake = FakeZenodo(concept=100, draft_id="333/../../x")
        code, _, err = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(code, 1)
        self.assertIn("not a valid identifier", err)
        self.assertFalse(any("../" in url for _, url, _ in fake.calls))


class IdempotenceTests(ZenodoTestCase):
    TAG_URL = "https://github.com/owner/repo/tree/spec-v0.1.0"

    def test_a_release_already_archived_is_not_published_a_second_time(self):
        related = [{"identifier": self.TAG_URL, "relation": "isSupplementTo", "scheme": "url"}]
        fake = FakeZenodo(concept=100, latest_related=related)
        code, _, err = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(code, 1)
        self.assertIn("already archived", err)
        self.assertEqual(fake.operations(), [("GET", "records/100")])

    def test_an_older_tag_in_the_latest_version_does_not_block_a_new_release(self):
        other = "https://github.com/owner/repo/tree/spec-v0.0.9"
        related = [{"identifier": other, "relation": "isSupplementTo", "scheme": "url"}, "junk", None]
        fake = FakeZenodo(concept=100, latest_related=related)
        code, _, _ = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(code, 0)

    def test_the_tag_url_is_the_one_written_by_a_run(self):
        # The guard above only works if what a run records is what the guard looks for.
        fake = FakeZenodo(concept=None)
        self.run_script(fake, self.env())
        recorded = [item["identifier"] for item in fake.metadata["related_identifiers"]]
        self.assertIn(self.TAG_URL, recorded)


class PublicationFailureTests(ZenodoTestCase):
    """Once the publish request is sent, the DOI exists or may exist: no failure may hide it."""

    def assert_reported_after_failure(self, fake, expected_in_stderr):
        code, out, err = self.run_script(fake, self.env())
        self.assertEqual(code, 3)
        self.assertIn(expected_in_stderr, err)
        self.assertIn("Published DOI: 10.5281/zenodo.777", out)
        summary = self.summary()
        self.assertIn("10.5281/zenodo.777", summary)  # the DOI of the version
        self.assertIn("`776`", summary)  # the concept record id to put in ZENODO_CONCEPT_RECID
        self.assertIn("ZENODO_CONCEPT_RECID", summary)
        self.assertIn("ne pas rejouer", summary)
        self.assertNotIn(TOKEN, summary)
        return summary

    def test_a_read_back_refused_by_zenodo_still_writes_the_summary(self):
        fake = FakeZenodo(concept=None, readback_status=500)
        summary = self.assert_reported_after_failure(fake, "Error after the publish request: FakeHTTPError")
        self.assertIn("Published deposition 777: DOI 10.5281/zenodo.777, concept record 776", self.last_out)
        self.assertIn("Anomalie après la publication", summary)

    def test_an_unexpected_record_link_still_writes_the_summary(self):
        for link in (
            "https://evil.example/api/records/777",
            "http://sandbox.zenodo.org/api/records/777",
            f"{API}/deposit/depositions/777",
            f"{API}/records/abc",
            f"{API}/records/777/../../x",
            12,
        ):
            with self.subTest(link=link):
                (self.tmp / "summary.md").unlink(missing_ok=True)
                fake = FakeZenodo(concept=None, record_link=link)
                self.assert_reported_after_failure(fake, "Error after the publish request: ZenodoError")
                self.assertFalse(any(url.startswith("https://evil.example") for _, url, _ in fake.calls))

    def test_a_lost_connection_after_publication_still_writes_the_summary(self):
        fake = FakeZenodo(concept=None, readback_error=ConnectionError(f"reset while using {TOKEN}"))
        summary = self.assert_reported_after_failure(fake, "Error after the publish request: ConnectionError")
        self.assertIn("***", summary)  # the token was redacted from the message

    def test_a_lost_answer_to_the_publish_request_is_reported_as_uncertain(self):
        fake = FakeZenodo(concept=None, publish_error=ConnectionError("timed out"))
        code, _, err = self.run_script(fake, self.env())
        self.assertEqual(code, 3)
        self.assertIn("ConnectionError", err)
        summary = self.summary()
        self.assertIn("publication INCERTAINE", summary)
        self.assertIn("dépôt 777", summary)
        self.assertIn("Vérifier sur Zenodo avant de rejouer", summary)

    def test_a_server_error_on_the_publish_request_is_uncertain_too(self):
        fake = FakeZenodo(concept=None, publish_status=503)
        code, _, _ = self.run_script(fake, self.env())
        self.assertEqual(code, 3)
        self.assertIn("publication INCERTAINE", self.summary())

    def test_a_publish_answer_that_is_not_an_object_is_uncertain(self):
        for payload in ([], "ok", None, 3):
            with self.subTest(payload=payload):
                (self.tmp / "summary.md").unlink(missing_ok=True)
                code, _, err = self.run_script(FakeZenodo(concept=None, publish_payload=payload), self.env())
                self.assertEqual(code, 3)
                self.assertIn("ZenodoError", err)
                self.assertIn("publication INCERTAINE", self.summary())

    def test_a_clean_refusal_of_the_publish_request_is_not_reported_as_a_publication(self):
        fake = FakeZenodo(concept=None, publish_status=400)
        with self.assertRaises(FakeHTTPError):
            self.run_script(fake, self.env())
        self.assertEqual(self.summary(), "")

    def test_a_summary_that_cannot_be_written_does_not_turn_a_success_into_a_failure(self):
        # GITHUB_STEP_SUMMARY names a directory: opening it for appending fails.
        fake = FakeZenodo(concept=None)
        code, out, err = self.run_script(fake, self.env(GITHUB_STEP_SUMMARY=str(self.tmp)))
        self.assertEqual(code, 0)
        self.assertIn("could not be written", err)
        self.assertIn("Published DOI: 10.5281/zenodo.777", out)


    def test_a_read_back_answer_that_is_not_an_object_still_writes_the_summary(self):
        for payload in ([], "ok", None, 3):
            with self.subTest(payload=payload):
                (self.tmp / "summary.md").unlink(missing_ok=True)
                fake = FakeZenodo(concept=None, readback_payload=payload)
                self.assert_reported_after_failure(fake, "Error after the publish request: ZenodoError")

    def test_an_interrupt_after_publication_prints_the_doi_and_is_not_swallowed(self):
        fake = FakeZenodo(concept=None, readback_error=KeyboardInterrupt())
        out, err = io.StringIO(), io.StringIO()
        with mock.patch.object(sync_zenodo, "requests", fake):
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                with self.assertRaises(KeyboardInterrupt):
                    sync_zenodo.run([], self.env())
        self.assertIn("Published DOI: 10.5281/zenodo.777", out.getvalue())
        self.assertIn("ne pas rejouer", self.summary())

    def test_an_interrupt_before_the_publish_request_is_not_reported_as_a_publication(self):
        class Interrupting(FakeRequests):
            def dispatch(self, method, url, **kwargs):
                raise KeyboardInterrupt()

        out, err = io.StringIO(), io.StringIO()
        with mock.patch.object(sync_zenodo, "requests", Interrupting()):
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                with self.assertRaises(KeyboardInterrupt):
                    sync_zenodo.run([], self.env())
        self.assertEqual(self.summary(), "")
        self.assertNotIn("Published DOI", out.getvalue())

    def test_a_report_that_fails_for_any_reason_is_a_warning_with_the_token_removed(self):
        boom = RuntimeError(f"boom {TOKEN}")
        with mock.patch.object(sync_zenodo, "summary", side_effect=boom):
            code, out, err = self.run_script(FakeZenodo(concept=None), self.env())
            self.assertEqual(code, 0)
            self.assertIn("could not be written: RuntimeError: boom ***", err)
            code, out, err = self.run_script(FakeZenodo(concept=None, readback_status=500), self.env())
            self.assertEqual(code, 3)  # the failure is not replaced by the reporting error
            self.assertIn("Published DOI: 10.5281/zenodo.777", out)

    def test_only_a_clear_refusal_of_the_publish_request_proves_that_nothing_was_published(self):
        for status in (400, 401, 403, 404, 422):
            with self.subTest(status=status), self.assertRaises(FakeHTTPError):
                self.run_script(FakeZenodo(concept=None, publish_status=status), self.env())
        for status in (408, 409, 429, 500, 502, 503):
            with self.subTest(status=status):
                (self.tmp / "summary.md").unlink(missing_ok=True)
                code, _, _ = self.run_script(FakeZenodo(concept=None, publish_status=status), self.env())
                self.assertEqual(code, 3)
                self.assertIn("publication INCERTAINE", self.summary())

    def test_the_token_is_removed_from_a_refusal_raised_before_the_publish_request(self):
        fake = FakeZenodo(concept=100, draft_link=f"https://evil.example/{TOKEN}")
        code, _, err = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        self.assertEqual(code, 1)
        self.assertIn("Refused:", err)
        self.assertIn("***", err)

    def test_a_response_body_cannot_start_a_workflow_command(self):
        response = FakeResponse(status=400, text="::add-mask::x\n  ::warning::y\nplain\x00end")
        err = io.StringIO()
        with contextlib.redirect_stderr(err), self.assertRaises(FakeHTTPError):
            sync_zenodo.check(response, "do something")
        lines = [line for line in err.getvalue().splitlines() if line]
        self.assertTrue(lines[0].startswith("Error while trying"))
        self.assertTrue(all(line.startswith("| ") for line in lines[1:]), lines)
        self.assertIn("| plain?end", lines)

    def run_script(self, fake, environ, argv=()):
        status, out, err = super().run_script(fake, environ, argv)
        self.last_out = out
        return status, out, err


class NewConceptAttemptTests(ZenodoTestCase):
    """NEW cannot notice that its record exists: a second attempt of the same run must not happen."""

    def test_new_with_the_first_attempt_is_accepted(self):
        fake = FakeZenodo(concept=None)
        code, _, _ = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="NEW", GITHUB_RUN_ATTEMPT="1"))
        self.assertEqual(code, 0)

    def test_new_on_a_rerun_is_refused_before_any_network_call(self):
        self.assert_refused_before_network(
            self.env(ZENODO_CONCEPT_RECID="NEW", GITHUB_RUN_ATTEMPT="2"), "must never be repeated"
        )

    def test_new_needs_the_attempt_counter_to_be_exactly_1(self):
        for value in (None, "", "0", "01", "10", "1 ", "1\n", "one", "2", "99"):
            with self.subTest(value=value):
                self.assert_refused_before_network(
                    self.env(ZENODO_CONCEPT_RECID="NEW", GITHUB_RUN_ATTEMPT=value), "GITHUB_RUN_ATTEMPT"
                )

    def test_the_configuration_check_applies_the_same_rule(self):
        self.assert_refused_before_network(
            self.env(ZENODO_CONCEPT_RECID="NEW", GITHUB_RUN_ATTEMPT="2"),
            "must never be repeated",
            argv=["--check-config"],
        )

    def test_a_declared_concept_may_be_published_on_any_attempt(self):
        fake = FakeZenodo(concept=100)
        env = self.env(ZENODO_CONCEPT_RECID="100", GITHUB_RUN_ATTEMPT="3")
        code, _, _ = self.run_script(fake, env)
        self.assertEqual(code, 0)


class MetadataFileTests(ZenodoTestCase):
    """A missing, empty or invalid zenodo.json must never become `{}`: it would be sent to Zenodo."""

    def assert_refused_config(self, message):
        self.assert_refused_before_network(self.env(), message)

    def test_a_missing_zenodo_json_is_refused(self):
        (self.tmp / "zenodo.json").unlink()
        self.assert_refused_config("zenodo.json is missing")

    def test_an_empty_or_invalid_zenodo_json_is_refused(self):
        for content in ("", "   \n", "{not json", "﻿{}", "null", "[]", '"text"', "3"):
            with self.subTest(content=content):
                (self.tmp / "zenodo.json").write_text(content, encoding="utf-8")
                self.assert_refused_config("zenodo.json")

    def test_creators_are_required(self):
        base = dict(BASE_ZENODO_JSON)
        for creators in (UNSET, None, [], "Pierre", [{}], [{"name": ""}], ["Pierre"], [{"orcid": "x"}]):
            with self.subTest(creators=creators):
                document = dict(base)
                if creators is UNSET:
                    del document["creators"]
                else:
                    document["creators"] = creators
                (self.tmp / "zenodo.json").write_text(json.dumps(document), encoding="utf-8")
                self.assert_refused_config("`creators`")

    def test_a_valid_zenodo_json_is_accepted(self):
        fake = FakeZenodo(concept=None)
        code, _, _ = self.run_script(fake, self.env())
        self.assertEqual(code, 0)

    def test_an_invalid_files_metadata_is_refused_but_a_missing_one_is_fine(self):
        for content in ("", "{not json", "[]"):
            with self.subTest(content=content):
                (self.tmp / "zenodo.files.json").write_text(content, encoding="utf-8")
                self.assert_refused_config("zenodo.files.json")
        (self.tmp / "zenodo.files.json").write_text(json.dumps({"out/k7pl-spec.pdf": "oops"}), encoding="utf-8")
        self.assert_refused_config("per-file metadata")
        (self.tmp / "zenodo.files.json").unlink()
        code, _, _ = self.run_script(FakeZenodo(concept=None), self.env())
        self.assertEqual(code, 0)

    def test_per_file_metadata_is_merged_over_the_shared_metadata(self):
        files = {"out/k7pl-spec.pdf": {"title": "From the files metadata"}}
        (self.tmp / "zenodo.files.json").write_text(json.dumps(files), encoding="utf-8")
        fake = FakeZenodo(concept=None)
        self.run_script(fake, self.env())
        self.assertEqual(fake.metadata["title"], "From the files metadata")
        self.assertEqual(fake.metadata["creators"], BASE_ZENODO_JSON["creators"])


class TagPrefixTests(ZenodoTestCase):
    def test_the_spec_v_prefix_is_really_required(self):
        # Each of these would pass the version pattern if only the first six characters were dropped.
        for tag in ("release-1.2.3", "svec-v0.1.0", "Spec-v0.1.0", "spec_v0.1.0", "spec-w0.1.0", "xxxxxx0.1.0"):
            with self.subTest(tag=tag):
                self.assert_refused_before_network(self.env(ZENODO_TAG=tag), "ZENODO_TAG")

    def test_the_prefix_is_removed_from_the_version(self):
        self.assertEqual(sync_zenodo.load_config(self.env(ZENODO_TAG="spec-v1.2.3-rc.1")).version, "1.2.3-rc.1")


class InheritedFileDeletionTests(ZenodoTestCase):
    def test_a_failed_deletion_of_an_inherited_file_stops_everything(self):
        fake = FakeZenodo(concept=100, delete_status=500)
        with self.assertRaises(FakeHTTPError):
            self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
        operations = fake.operations()
        self.assertIn(("DELETE", "deposit/depositions/333/files/oldfile"), operations)
        self.assertNotIn(("POST", "deposit/depositions/333/files"), operations)  # nothing uploaded
        self.assertNotIn(("POST", "deposit/depositions/333/actions/publish"), operations)


class ChecksumListingFallbackTests(ZenodoTestCase):
    def test_a_checksum_only_in_the_file_listing_is_used_and_verified(self):
        fake = FakeZenodo(concept=None, checksum="listing-md5")
        code, out, _ = self.run_script(fake, self.env())
        self.assertEqual(code, 0)
        self.assertIn("checksum matches the local file", out)
        listings = [op for op in fake.operations() if op == ("GET", "deposit/depositions/777/files")]
        self.assertEqual(len(listings), 2)  # before the upload, then the fallback after it

    def test_a_wrong_checksum_in_the_file_listing_stops_before_publication(self):
        fake = FakeZenodo(concept=None, checksum="listing-wrong")
        code, _, err = self.run_script(fake, self.env())
        self.assertEqual(code, 1)
        self.assertIn("differs from the local file", err)
        self.assertNotIn(("POST", "deposit/depositions/777/actions/publish"), fake.operations())


class DefaultEnvironmentTests(ZenodoTestCase):
    """`run()` without an `environ` argument reads `os.environ`."""

    def test_check_config_reads_os_environ(self):
        out = io.StringIO()
        with mock.patch.dict(os.environ, self.env(), clear=True), contextlib.redirect_stdout(out):
            self.assertEqual(sync_zenodo.run(["--check-config"]), 0)
        self.assertIn("Configuration OK", out.getvalue())

    def test_a_refusal_reads_os_environ_too(self):
        err = io.StringIO()
        with mock.patch.dict(os.environ, self.env(ZENODO_CONCEPT_RECID="abc"), clear=True):
            with contextlib.redirect_stderr(err):
                self.assertEqual(sync_zenodo.run(["--check-config"]), 2)
        self.assertIn("ZENODO_CONCEPT_RECID", err.getvalue())

    def test_a_publication_reads_os_environ_and_writes_the_summary_it_names(self):
        fake = FakeZenodo(concept=None)
        out = io.StringIO()
        with mock.patch.dict(os.environ, self.env(), clear=True), mock.patch.object(sync_zenodo, "requests", fake):
            with contextlib.redirect_stdout(out):
                self.assertEqual(sync_zenodo.run([]), 0)
        self.assertIn("10.5281/zenodo.777", self.summary())


STUB_REQUESTS = '''
class HTTPError(Exception):
    pass


def _network(*args, **kwargs):
    raise AssertionError("network access attempted")


get = post = put = delete = _network
'''


class ProcessTests(ZenodoTestCase):
    """The script as a command, from the repository root: its exit status is what the job sees."""

    def run_command(self, environ, *args):
        stub = self.tmp / "stub"
        stub.mkdir(exist_ok=True)
        (stub / "requests.py").write_text(STUB_REQUESTS, encoding="utf-8")  # no pip, no network
        env = {
            "PATH": os.environ.get("PATH", ""),
            "LANG": "C.UTF-8",
            "PYTHONPATH": str(stub),
            "PYTHONDONTWRITEBYTECODE": "1",
            **environ,
        }
        return subprocess.run(
            [sys.executable, str(SCRIPTS / "sync_zenodo.py"), *args],
            cwd=SCRIPTS.parent,
            env=env,
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )

    def test_exit_status_0_for_a_valid_configuration(self):
        result = self.run_command(self.env(ZENODO_TOKEN=None), "--check-config")
        self.assertEqual((result.returncode, result.stderr), (0, ""))
        self.assertIn("Configuration OK", result.stdout)

    def test_exit_status_2_for_an_invalid_configuration(self):
        result = self.run_command(self.env(ZENODO_CONCEPT_RECID=None))
        self.assertEqual(result.returncode, 2)
        self.assertIn("ZENODO_CONCEPT_RECID is not set", result.stderr)

    def test_exit_status_2_for_a_repeated_new(self):
        result = self.run_command(self.env(ZENODO_CONCEPT_RECID="NEW", GITHUB_RUN_ATTEMPT="2"))
        self.assertEqual(result.returncode, 2)
        self.assertIn("must never be repeated", result.stderr)

    def test_exit_status_1_without_a_pdf_and_no_network_call(self):
        (self.tmp / "out" / "k7pl-spec.pdf").unlink()
        result = self.run_command(self.env(ZENODO_FILES_DIR=str(self.tmp / "out")))
        self.assertEqual(result.returncode, 1)
        self.assertIn("No PDF found", result.stderr)
        self.assertNotIn("network access attempted", result.stderr)

    def test_a_usage_error_has_exit_status_2(self):
        result = self.run_command(self.env(), "--no-such-option")
        self.assertEqual(result.returncode, 2)
        self.assertIn("usage:", result.stderr)


class InheritedFileTests(ZenodoTestCase):
    def test_a_file_id_that_is_not_a_plain_token_is_never_placed_in_a_url(self):
        for bad in ("../../x", "a/b", "", "a b", None, 12, "x?y=1"):
            with self.subTest(file_id=bad):
                fake = FakeZenodo(concept=100, old_file_id=bad)
                code, _, err = self.run_script(fake, self.env(ZENODO_CONCEPT_RECID="100"))
                self.assertEqual(code, 1)
                self.assertIn("file id is not valid", err)
                self.assertNotIn("DELETE", [method for method, _ in fake.operations()])
                self.assertNotIn(("POST", "deposit/depositions/333/actions/publish"), fake.operations())


class ChecksumTests(ZenodoTestCase):
    def test_a_checksum_that_differs_from_the_local_file_stops_before_publication(self):
        fake = FakeZenodo(concept=None, checksum="wrong")
        code, _, err = self.run_script(fake, self.env())
        self.assertEqual(code, 1)
        self.assertIn("differs from the local file", err)
        self.assertNotIn(("POST", "deposit/depositions/777/actions/publish"), fake.operations())

    def test_a_matching_checksum_is_accepted_bare_or_prefixed(self):
        for style in ("md5", "md5-prefixed"):
            with self.subTest(style=style):
                fake = FakeZenodo(concept=None, checksum=style)
                code, out, _ = self.run_script(fake, self.env())
                self.assertEqual(code, 0)
                self.assertIn("checksum matches the local file", out)

    def test_an_absent_checksum_is_reported_as_not_verified_not_as_verified(self):
        for style in ("none", "garbage"):
            with self.subTest(style=style):
                fake = FakeZenodo(concept=None, checksum=style)
                code, out, _ = self.run_script(fake, self.env())
                self.assertEqual(code, 0)
                self.assertIn("not verified", out)
                self.assertNotIn("matches the local file", out)
                self.assertIn("not verified", self.summary())

    def test_parse_checksum(self):
        parse = sync_zenodo.parse_checksum
        self.assertEqual(parse(PDF_MD5), ("md5", PDF_MD5))
        self.assertEqual(parse(f"md5:{PDF_MD5.upper()}"), ("md5", PDF_MD5))
        self.assertEqual(parse(PDF_SHA256), ("sha256", PDF_SHA256))
        self.assertEqual(parse(f"sha256:{PDF_SHA256}"), ("sha256", PDF_SHA256))
        for bad in (None, 5, "", "md5:", "md5:zz", f"sha1:{'a' * 40}", "a" * 31, f"md5:{PDF_SHA256}"):
            with self.subTest(value=bad):
                self.assertIsNone(parse(bad))


class IdentifierTests(unittest.TestCase):
    def config(self):
        return sync_zenodo.load_config(
            {
                "ZENODO_TOKEN": TOKEN,
                "ZENODO_ENV": "sandbox",
                "ZENODO_CONCEPT_RECID": "NEW",
                "ZENODO_TAG": TAG,
                "ZENODO_COMMIT": COMMIT,
                "ZENODO_REPOSITORY": "owner/repo",
                "ZENODO_RELEASE_URL": RELEASE_URL,
                "GITHUB_RUN_ATTEMPT": "1",
            }
        )

    def test_as_id_accepts_only_positive_integers(self):
        self.assertEqual(sync_zenodo.as_id(12, "x"), 12)
        self.assertEqual(sync_zenodo.as_id("12", "x"), 12)
        for bad in (True, 0, -1, "0", "012", "1/2", "12 ", "1.0", 1.5, None, [1], "٣"):
            with self.subTest(value=bad), self.assertRaises(sync_zenodo.ZenodoError):
                sync_zenodo.as_id(bad, "x")

    def test_id_from_link_requires_the_configured_host_and_collection(self):
        config = self.config()
        ok = f"{API}/deposit/depositions/42"
        self.assertEqual(sync_zenodo.id_from_link(config, ok, "deposit/depositions", "link"), 42)
        for bad in (
            ok.replace("sandbox.", ""),
            ok.replace("https", "http"),
            ok + "/files",
            ok + "x",
            ok + "?x=1",
            f"{BASE}:444/api/deposit/depositions/42",
            f"{API}/records/42",
            "",
            None,
        ):
            with self.subTest(link=bad), self.assertRaises(sync_zenodo.ZenodoError):
                sync_zenodo.id_from_link(config, bad, "deposit/depositions", "link")


if __name__ == "__main__":
    unittest.main()
