# SPDX-FileCopyrightText: 2026 Cyprien PIERRE
#
# SPDX-License-Identifier: CECILL-2.1
from pathlib import Path
import argparse, datetime, os, subprocess

from controles import couverture

def sh(*args):
    return subprocess.check_output(args, text=True).strip()

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--output", default="docs/STATUS.md")
    p.add_argument("--verification", default=os.environ.get("K7PL_VERIFICATION", "unknown"))
    a = p.parse_args()
    commit = sh("git", "rev-parse", "HEAD")
    date = sh("git", "show", "-s", "--format=%cI", "HEAD")
    toolchain = Path("lean-toolchain").read_text().strip()
    version = "unknown"
    lake = Path("lakefile.lean").read_text()
    marker = 'version := "'
    if marker in lake:
        version = lake.split(marker, 1)[1].split('"', 1)[0]
    src = sh("bash", "-lc", "find src -type f -name '*.lean' | wc -l")
    tests = sh("bash", "-lc", "find tests -type f -name '*.lean' | wc -l")
    spec = sh("bash", "-lc", "find spec -type f -name '*.lean' | wc -l")
    verification = a.verification.upper()
    generated = datetime.datetime.fromisoformat(date.replace("Z", "+00:00")).date().isoformat()
    lines = [
        "<!-- GENERATED CONTENT START -->",
        "<!--",
        "GENERATED FILE: do not edit manually.",
        "Source: scripts/generate_status.py",
        "-->",
        "",
        "# K7PL Status",
        "",
        "This document is generated by CI from repository facts and the CI verification gate.",
        "",
        "**Generated for commit:** " + commit,
        "**Commit date:** " + date,
        "**Generated date:** " + generated,
        "**Implementation version:** " + version,
        "**Lean toolchain:** " + toolchain,
        "",
        "## CI verification",
        "",
        "| Fact | Status |",
        "|---|---|",
        "| Verification gate | " + verification + " |",
        "| Lean build, tests, lint, and axiom audit | " + verification + " |",
        "| Specification build and rendering | " + verification + " |",
        "| Repository, documentation, and security checks | " + verification + " |",
        "",
        "CI success means that the configured checks ran for the applicable impact scope; it does not establish correctness of every scientific claim.",
        "",
        "## Repository facts",
        "",
        "| Fact | Value |",
        "|---|---:|",
        "| Lean source files under src/ | " + src + " |",
        "| Lean test files under tests/ | " + tests + " |",
        "| Lean specification modules under spec/ | " + spec + " |",
        "",
        "These counts are generated from the current Git tree and are not estimates of formalisation completeness.",
        "",
        "## Scientific status",
        "",
        "See [ASSURANCE.md](ASSURANCE.md) for scientific status. CI success does not imply specification coherence, complete specification/formalisation correspondence, or implementation conformance.",
        "",
        "## Generation",
        "",
        "The authoritative generator is [scripts/generate_status.py](../scripts/generate_status.py). CI is responsible for updating this file; manual edits are not part of the project workflow."
    ]
    Path(a.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    couverture.update_status()

if __name__ == "__main__":
    main()
